version: "3.8"
services:
    chordNode:
      build:
         context: ../chordNode/
         dockerfile: Dockerfile
      image: chord_node:v1.0
      networks: 
        - chord
      deploy:
        replicas: "${NODE_REPLICAS}"
        resources:
          limits:
            cpus: '0.5'
            memory: 100m
      entrypoint: ["python3","/opt/chordNode/chordNode.py"]
        # - "watchmedo"
        # - "shell-command"
        # - "--patterns='*.py'"
        # - "--recursive"
        # - "--command='python3 /opt/chordNode/chordNode.py'"
        # - "/opt/chordNode/"
      environment:
        - FT_SIZE=7
      tty: true
      volumes: 
          - ChordNodeData:/opt/chordNode/Data
          - ChordNodeCode:/opt/chordNode/

networks: 
    chord: 
        name: chord-net
        external: true

volumes:
    ChordNodeData:
        external: true
    ChordNodeCode:
        name: ChordNodeCode
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/up1072498/Projects/Chord/init_node/ChordNodeCode