version: "3.8"

services:
    chordNode:
      build:
         context: ../chordNode/
         dockerfile: Dockerfile
      image: ubuntu:latest
      networks: 
        - chord
      deploy:
        replicas: "${NODE_REPLICAS}"
        resources:
          limits:
            cpus: '0.5'
            memory: 100m
      entrypoint: ["/bin/bash","-c","tail","-f","/dev/null"]
      tty: true
      volumes: 
          - ChordNodeData:/opt/chordNode

networks: 
    chord: 
        name: chord-net
        external: true

volumes:
    ChordNodeData:
        external: true