chord:
    network_var: "NET_NAME"
    container_var: "CNAME"
    exp: "EXPONENT"

data_cache: "DATA_PRESENT"
crawler:
    englishalph_cardinality: 26
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)  Edg/118.0.2088.61"
    page_title: "List of computer scientists"
    details: ["alma_mater","education","awards", "prizes"]
    
   
